title: Power BI Examples
description: A collection of interesting Power BI examples with DAX and Power Query code
# baseurl: "/Power-BI-Examples" # Temporarily commented out for troubleshooting
url: "https://joshlevent.github.io"

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs@v0.3.3
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Theme settings
color_scheme: dark
heading_anchors: true
search_enabled: true
color_scheme_toggle: true
enable_copy_code_button: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - "*.pbix.temp"
  - "*.pbix.backup"

# Collections
collections:
  examples:
    output: true
    permalink: /examples/:path/

# Default front matter
defaults:
  - scope:
      path: "examples/*/"
      type: "pages"
    values:
      layout: "page"
      parent: "Examples"
      has_toc: false
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "examples/index.md"
    values:
      layout: "page"
      title: "Examples"
      nav_order: 2
      has_children: true
      has_toc: false
  - scope:
      path: "license.md"
    values:
      layout: "page"
      title: "License"
      nav_order: 99

# Site settings
locale: "en-US"

# Author
author:
  name: Josh Levent
  email: josh@joshlevent.com
  url: https://joshlevent.com
  github: joshlevent
