title: Power BI Examples
description: A collection of practical Power BI examples and solutions to common data analysis challenges
baseurl: "/Power-BI-Examples"
url: "https://joshlevent.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - LICENSE
  - "*.pbix"
  - "*.pbix.temp"
  - "*.pbix.backup"
  - index.md
  - _examples
