title: Power BI Examples
description: A collection of interesting Power BI examples with DAX and Power Query code
baseurl: "/Power-BI-Examples"
url: "https://joshlevent.github.io"

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs@v0.7.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Theme settings
color_scheme: dark
search_enabled: true
heading_anchors: true

# Enable or disable the site search
search:
  # Split pages into sections that can be searched individually
  heading_level: 2
  # Maximum amount of previews per search result
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  preview_words_after: 10
  # Set the search token separator
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  button: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - "*.pbix.temp"
  - "*.pbix.backup"

# Collections
collections:
  examples:
    output: true
    permalink: /examples/:path/

# Default front matter
defaults:
  - scope:
      path: "examples/*/"
      type: "pages"
    values:
      layout: "page"
      parent: "Examples"
      has_toc: false
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "examples/index.md"
    values:
      layout: "page"
      title: "Examples"
      nav_order: 2
      has_children: true
      has_toc: false
  - scope:
      path: "license.md"
    values:
      layout: "page"
      title: "License"

# Site settings
locale: "en-US"
search_full_content: true

# Author
author:
  name: Josh Levent
  email: josh@joshlevent.com
  url: https://joshlevent.com
  github: joshlevent
